services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 2110
      MYSQL_DATABASE: youtube_api
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 2110
      DB_NAME: youtube_api

volumes:
  mysql-data:
